version: '3'
services:
  np-exploration:
    image: pgnp:latest
    container_name: exploration
    ports:
      - "42666:42666"
    environment:
      - PGPORT=42666
      - POSTGRES_DB=noisepage
      - POSTGRES_USER=noisepage
      - POSTGRES_PASSWORD=terrier
      - NP_REPLICATION_TYPE=exploratory
    volumes:
      - pgdata-exploration:/pgdata
volumes:
  pgdata-exploration:
    external: true
